Fix node locking for webdav
openkm/document-management-system pull request #260
Opened 2020-11-08 08:31 UTC by sbingner

This makes the locking only break writing a file if it's locked to somebody else.  This workaround allows writing files from Windows over WebDav

2020-11-08 08:32 UTC, sbingner commented
NOTE: Previously provided this patch at https://forum.openkm.com/viewtopic.php?p=41311&sid=8a28cda917b66723aeaf7423745899c5#p41311

2020-11-09 07:49 UTC, darkman97i requested changes
You should consider there're two types of lock:
* Lock node because you do not want to be modified by nobody ( included the user who lock the node )
* Lock by edition process. 

In case of edition, your logic will be fine, allow continue editing because you are the editor, in case hard lock ( option 1 ) you should continue raising the error. You can check if the lock is for edition or not with 

```java
NodeDocument nDoc = (NodeDocument) session.load(NodeDocument.class, uuid);
    NodeLock nLock = nDoc.getLock();
    if (!nLock.getOwner().equals(user)) {
        throw new LockException("Node already locked by another user");
    }
} else {
    throw new LockException("Node already locked");
}

2020-11-11 01:42 UTC, sbingner commented
Looking at the source, the place where the change was made seems to already handle the first case before calling this lock function as it accepts a NodeDocument as the argument.  If you lock it from the GUI it still does not allow writing, and if it failed to get the nDoc in the function calling it due to a node lock it should already have an exception caught at that point which I did verify does not allow node locked documents to be edited from WebDav...

Am I missing something?

2020-11-11 07:20 UTC, darkman97i commented
There's a missing line to check is the node isCheckout, because node might be locked by lock feature or by edition. Checkout and Hard lock are not the same lock type ( although both are locked ).

2020-12-21 11:34 UTC, merged